export const ReviewsData = [
  {
    img: "https://judgeme.imgix.net/burgerbae/1688465145__img20230625131642__original.jpg?auto=format",
    rating: 5,
    name: "Devika L.",
    verified: true,
    heading: "Awesome fit",
    description:
      "If you like short dresses then you can go for it. It fits really well and looks amazing.",
    about: "Vernocia Dress (Women BodyCon Square Neck Dress) : All Colours For Women",
    date: "02/15/2026"
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1746169276__img_2366__original.jpeg?auto=format",
    rating: 5,
    name: "Vikas V.",
    verified: true,
    heading: "I loved it",  
    date: "02/15/2026",
    about:"Matrix Acid Wash Drop Sleeved Tee",
    description:
      "Amazing fabric and very comfortable. Totally worth the price.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1736404491__img_8235__original.jpeg?auto=format",
    rating: 5,
    name: "Sindhu R.",
    verified: true,
    date: "02/15/2026",
    heading: "Amazing",
    description: "Very good quality and material of the product. Loved it.",
    about:"The Fly Jacket"
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1735219583__snapchat-695724802__original.jpg?auto=format",
    rating: 5,
    name: "Vanshika S.",
    verified: true,
    date: "02/15/2026",
    heading: "Amazing fit!!",
    about:"Glory jacket for Women",
    description: "Loved the product ❤️ Amazing fit and looks premium.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1688279306__img_3421__original.jpeg?auto=format",
    rating: 5,
    name: "Maya S.",
    verified: true,
    heading: "I just love it",
    date: "02/15/2026",
    description:
      "The best thing is that the dress is pure cotton and super comfy.",
    about: "Tennis Dress : Burger Bae Bodycon V: Neck Collar Dress(Bright Orange) For Women"
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1687949273__img_5403__original.jpeg?auto=format",
    rating: 4,
    name: "Ritika M.",
    verified: true,
    heading: "Very comfortable",
    date: "02/15/2026",
    about:"Gym Tank For Women",
    description:
      "Fabric is soft and breathable. Slightly loose but still looks great.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1734716086__img_8465__original.jpg?auto=format",
    rating: 5,
    name: "Aman K.",
    verified: false,
    date: "02/15/2026",
    heading: "Great quality",
    about:"Tokyo Revengers : Heavyweight Baggy Sweatshirt for Men And Women",
    description: "Quality exceeded my expectations. Will order again.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1687949273__img_5403__original.jpeg?auto=format",
    rating: 4,
    name: "Neha P.",
    verified: true,
    date: "02/15/2026",
    heading: "Nice fabric",
    about:"The Billie Eillish Cartoon Art Drop For Men and Women",
    description: "Material feels premium and stitching is neat.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1746169276__img_2366__original.jpeg?auto=format",
    rating: 5,
    name: "Karan J.",
    verified: true,
    date: "02/15/2026",
    about:"Travis Scott Stop Trying To Be God : Heavyweight Baggy Hoodie For Men",
    heading: "Perfect fit",
    description: "The size was perfect and the design looks really cool.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1685819242__inbound4810578422970758751__original.jpg?auto=format",
    rating: 4,
    name: "Anjali T.",
    verified: false,
    date: "02/15/2026",
    about: "Bomber Set Plum For Women",
    heading: "Looks stylish",
    description: "Looks very stylish. Got a lot of compliments wearing it.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1688037940__529c8d52-469a-41ea-a303-4a681dd48e84__original.jpeg?auto=format",
    rating: 5,
    name: "Pooja N.",
    verified: true,
    date: "02/15/2026",
    heading: "Loved the color",
    about:"London Corset Top ",
    description:
      "Color is exactly as shown in the pictures. Fabric feels great.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1688195812__07c2ae62-47b0-43a7-8381-838a992180e8__original.jpeg?auto=format",
    rating: 5,
    name: "Rahul D.",
    verified: true,
    date: "02/15/2026",
    heading: "Worth buying",
    about:"Lazy Boy Seoul Cargo Tracks For Men",
    description: "Comfortable, trendy, and good quality. Worth every penny.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1687401604__73ee276e-9249-44e9-be03-3bb9d45cf1dc__original.jpeg?auto=format",
    rating: 4,
    name: "Sneha B.",
    verified: true,
    date: "02/15/2026",
    heading: "Nice overall",
    about:"Burger Parachute Pants For Women",
    description: "Nice fit and material. Delivery was quick too.",
  },
  {
    img: "https://judgeme.imgix.net/burgerbae/1736404491__img_8235__original.jpeg?auto=format",
    rating: 5,
    name: "Arjun S.",
    verified: false,
    date: "02/15/2026",
    heading: "Super comfy",
    about:"Weekend Tracks For Men And Women",
    description: "Super comfortable and perfect for daily wear.",
  },
];
